### ISSUE TITLE
REP: Permissions per object

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1452]
There should be possibility to specify permissions on object level (a'la Regions in old Ralph).

Requirements:
- permissions should be easily defined (similar form to django-rules)
- permissions should be applied on single object and on list of objects too
- performance - when permissions are checked on list of objects, it should be done as filter on ORM side
- permissions should be checked when using:
  - django admin
  - API
  - importer / exporter
- permissions for related objects should be validated too (ex. if I have rights to save object with selected region)

Example usage of this permissions will be regions mechanism, applied on BO Asset, Licence and Support models (and, of course, user). Only users with selected region could view and change asset/licence/region with the same region. User could only assign region which is assigned to him.

Resources:
https://www.djangopackages.com/grids/g/perms/

**Comment by mkurek** [comment]
There will be 5 PRs for this issue:
- [x] mechanism + regions implementation at django-admin level: #1709 
- [x] implementation of permissions per object at API level (+ simple usage with regions): #1717  
- [ ] implementation of permissions per object at importer/exporter level (+ simple usage with regions): `<work in progress>`
- [x] data importer for regions: #1741
- [x] data exporter for regions (+ minor changes in supports and licences, ex. additional_notes -> remarks): #1738

**Comment by romcheg** [comment]
Closing a stale proposal since we don't plan doing this in the observable future.
